# Generated by Django 4.2.7 on 2025-10-23 19:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Service name (e.g., 'Classic Manicure')", max_length=100)),
                ('category', models.CharField(choices=[('nails', 'Nails'), ('lashes', 'Lashes'), ('both', 'Both')], help_text='Service category', max_length=10)),
                ('description', models.TextField(help_text='Detailed service description')),
                ('price', models.DecimalField(decimal_places=2, help_text='Service price', max_digits=8, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('duration_minutes', models.PositiveIntegerField(help_text='Service duration in minutes')),
                ('is_featured', models.BooleanField(default=False, help_text='Show on homepage')),
                ('is_active', models.BooleanField(default=True, help_text='Available for booking')),
                ('image', models.ImageField(blank=True, help_text='Service image', null=True, upload_to='services/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['category', 'name'],
            },
        ),
    ]
