# Generated by Django 4.2.7 on 2025-11-02 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='second_image',
            field=models.ImageField(blank=True, help_text='Second image (for combined services - displays side by side with main image)', null=True, upload_to='services/'),
        ),
    ]
