# Generated by Django 4.2.7 on 2025-10-23 19:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(help_text="Client's name (can be first name only)", max_length=100)),
                ('client_photo', models.ImageField(blank=True, help_text='Client photo (optional)', null=True, upload_to='testimonials/')),
                ('service_category', models.CharField(choices=[('nails', 'Nails'), ('lashes', 'Lashes'), ('both', 'Both')], help_text='Service category reviewed', max_length=10)),
                ('rating', models.PositiveIntegerField(help_text='Rating from 1 to 5 stars', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('review_text', models.TextField(help_text='Client review text')),
                ('is_featured', models.BooleanField(default=False, help_text='Show on homepage')),
                ('is_approved', models.BooleanField(default=True, help_text='Approved for display')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
                'ordering': ['-is_featured', '-rating', '-created_at'],
            },
        ),
    ]
