# Generated by Django 4.2.7 on 2025-10-23 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Image title', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Image description')),
                ('category', models.CharField(choices=[('nails', 'Nails'), ('lashes', 'Lashes'), ('before_after', 'Before & After'), ('studio', 'Studio'), ('other', 'Other')], help_text='Image category', max_length=20)),
                ('image', models.ImageField(help_text='Gallery image', upload_to='gallery/')),
                ('thumbnail', models.ImageField(blank=True, help_text='Thumbnail image (auto-generated if not provided)', null=True, upload_to='gallery/thumbnails/')),
                ('is_featured', models.BooleanField(default=False, help_text='Show on homepage')),
                ('is_active', models.BooleanField(default=True, help_text='Visible in gallery')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Sort order (higher = first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Gallery Image',
                'verbose_name_plural': 'Gallery Images',
                'ordering': ['-sort_order', '-is_featured', '-created_at'],
            },
        ),
    ]
