# Generated by Django 4.2.7 on 2025-11-02 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='comparison_image',
            field=models.ImageField(blank=True, help_text="Comparison image (for 'Before & After' category - displays side by side)", null=True, upload_to='gallery/'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='category',
            field=models.CharField(choices=[('nails', 'Nails'), ('lashes', 'Lashes'), ('before_after', 'Before & After'), ('other', 'Other')], help_text='Image category', max_length=20),
        ),
    ]
