# Generated by Django 4.2.7 on 2025-11-02 02:49

from django.db import migrations


def convert_studio_to_other(apps, schema_editor):
    """Convert all existing 'studio' category items to 'other'."""
    GalleryImage = apps.get_model('gallery', 'GalleryImage')
    GalleryImage.objects.filter(category='studio').update(category='other')


def reverse_convert(apps, schema_editor):
    """Reverse migration: convert 'other' back to 'studio' (not recommended)."""
    GalleryImage = apps.get_model('gallery', 'GalleryImage')
    # Note: We can't reliably reverse this since we don't know which 'other' items were originally 'studio'
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_galleryimage_comparison_image_and_more'),
    ]

    operations = [
        migrations.RunPython(convert_studio_to_other, reverse_convert),
    ]
